on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v3
        with:
          operation: 'status'
          classpath: 'example/changelogs'
          changeLogFile: 'changelog1.xml'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: ${{ secrets.URL }}
  #        liquibaseProLicenseKey: ${{ secrets.LIQUIBASE_PRO_LICENSE_KEY}}