on: workflow_dispatch

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Generate Liquibase_HR changeLogFile
    steps:
      - uses: actions/checkout@v3
      - uses: liquibase/liquibase-github-action@v3
        with:
          operation: 'generate-changelog'
          classpath: 'example/changelogs'
          changeLogFile: 'changelog1.xml'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: ${{ secrets.URL }}