on: workflow_dispatch
jobs:
  Generate-ChangeLog:
    runs-on: ubuntu-latest
    name: Generate-ChangeLog
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'generatechangelog'
          classpath: 'example/changelogs'
          changeLogFile: 'changelog.xml'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: ${{ secrets.URL }}